print("Durga785".isalnum())
print('DURGA'.isalpha())
print('DURGA78'.isalpha())
print('durga'.isalpha())
print("9309777977".isdigit())
print("shubham".islower())
print("SHUBHAM".isupper())
print("Shubham Rajendra Chaudhari".istitle())
print(' '.isspace())